### ISSUE TITLE
":require" not keeping ".wisp" extension

### ISSUE THREAD

**Issue by girvo** [conradz/wispify#2]
So, this is a bit of a weird one; I'm attempting to use `wispify` in [Webpack](https://webpack.github.io/) by leveraging the [transform-loader](https://github.com/webpack/transform-loader).

Now, first off: it works! I'm quite impressed actually, it's working very well, for single `.wisp` entry-points anyway. `:require` even works, which is impressive!

However, attempting to load a relative path fails. An example:

``` clojure
; src/index.wisp
(ns wispify.index
  "a test for wisipfy + webpack"
  (:require [domchanger]
            [wispify.hello]))
```

``` clojure
; src/hello.wisp
(ns wispify.hello
  "a test of local imports")

(console.log "Hello, from imports")
```

With the following Webpack config:

```
// webpack.config.js
module.exports = {
    entry: './src/index.wisp',

    output: {
        path: __dirname,
        filename: 'bundle.js'
    },

    module: {
        loaders: [
            { 
                test: /\.css$/, 
                loader: 'style!css' 
            },
            {
                test: /\.wisp$/,
                loader: 'transform/cacheable?wispify'
            }
        ]
    },
};
```

The error given is as follows:

``` sh
Version: webpack 1.12.2
Time: 25ms
    Asset     Size  Chunks             Chunk Names
bundle.js  17.3 kB       0  [emitted]  main
chunk    {0} bundle.js (main) 14.9 kB [rendered]
    [0] ./src/index.wisp 1.73 kB {0} [built] [1 error]
     + 1 hidden modules

ERROR in ./src/index.wisp
Module not found: Error: Cannot resolve 'file' or 'directory' ./hello in /Users/josh/Work/Projects/wisp-webpack/src
 @ ./src/index.wisp 7:24-42
```

Now, the `require` call generated for local modules seems to be, at least in this case: `var _hello = require('./hello')` -- dropping the `.wisp` extension that Webpack requires to be able to configure the `transform-loader`.

I know that this is a Browserify module, but I thought I'd post the issue to see if you had any suggestions as to where I should look to start tackling this problem :)

Thanks!

**Comment by girvo** [comment]
Quickest update ever: I wrote my own "loader" for Webpack, though it's rudimentary as hell and munges the compiled JS on the fly to add the `.wisp` extension:

``` javascript
var path = require('path');
var wisp_compiler = require('wisp/compiler'); 

module.exports = function(source) {
    this.cacheable();
    var raw = wisp_compiler.compile(source, { 'source-uri': this.resourcePath });

    // Munge the result to fix local requires, to load through .wisp for WebPack
    var result = raw['code'].replace(/require\(\'\.(.*)\'\);/, function(match, capture) {
        return 'require(\'.' + capture + '.wisp\');';
    });

    return result;
};
```

Ew. But it works!

**Comment by conradz** [comment]
If you have a loader working in Webpack, just add it to [`resolve.extensions`](http://webpack.github.io/docs/configuration.html#resolve-extensions) in you config file like this:

``` js
// webpack.config.js
module.exports = {
  // ...
  resolve: {
    extensions: ["", ".webpack.js", ".web.js", ".js", ".wisp"]
  }
}
```

Hope that helps!

**Comment by girvo** [comment]
@conradz That works beautifully! Now I don't have to munge strings in my loader lol. Well done, thanks!
