### ISSUE TITLE
:require doesn't work

### ISSUE THREAD

**Issue by rtomsick** [conradz/wispify#3]
Similar to issue #2 , :require doesn't seem to work correctly when running under browserify.

As I understand it, the form

```
(:require foo.bar)
```

for a module in the 'foo' ns winds up getting translated  to 

```
require("./../bar");
```

Which is a problem, since the lack of a ".wisp" extension means that node's module loader will then look for "./../bar.{js|json|}"... so if I have a file at "./../bar.wisp" then it won't get found (and thus won't be transpiled by wispify).

I'm not sure how to resolve this easily.  require.extensions is deprecated (for poor reasons, as far as I'm concerned) and short of modifying the wisp compiler I'm not sure what's the best approach.

This might be solvable through some sort of hack in wispify, like wrapping the resulting output in a fn that locally redefines require() to check if a ".wisp" version of the path exists and if so appends the extension to the string that it passes through to node's require... but that's kinda an ugly hack.  That's the best I've got at the moment though...

It's a pity, because aside from that wisp seems to work out excellently!

**Comment by conradz** [comment]
You can use the browserify option `--extension=.wisp`. This will make browserify behave like you described, without any ugly hacks.
